function res = accuracy(y, yp)
% Высчитывание качественных характеристик обучения
    SSE = sum((y - yp) .^ 2);
    SSyy = sum((y - mean(y)) .^ 2);
    R_square = 1 - SSE/SSyy;

    MSE = mse(y - yp);

    RMSE = sqrt(MSE);

    CKO = RMSE / (max(y) - min(y)) * 100;

    MAE = mae(y - yp);

    MinAE = min(abs(y - yp));
    MaxAE =  max(abs(y - yp));

    MAPE = mean(abs((y - yp) ./ y)) * 100;

    errors = abs((y - yp) ./ y) * 100; % вектор относительных ошибок

    res = sprintf(['R квадрат: %f\n' ...
                   'MSE: %f\n' ...
                   'RMSE: %f\n' ...
                   'Относительная СКО: %f%%\n' ...
                   'MAE: %f\n'...
                   'min abs err: %f\n' ...
                   'max abs err: %f\n' ...
                   'MAPE: %f\n' ...
                   'Доля с ошибкой менее 5%%: %f%%\n' ...
                   'Доля с ошибкой от 5%% до 10%%: %f%%\n'...
                   'Доля с ошибкой от 10%% до 20%%: %f%%\n' ...
                   'Доля с ошибкой от 20%% до 30%%: %f%%\n' ...
                   'Доля с ошибкой более 30%%: %f%%\n'], ...
                   R_square, MSE, RMSE, CKO, MAE, MinAE, MaxAE, MAPE, ...
                   sum(errors < 5) / length(y) * 100, ...
                   sum(5 <= errors & errors < 10) / length(y) * 100, ...
                   sum(10 <= errors & errors < 20) / length(y) * 100, ...
                   sum(20 <= errors & errors < 30) / length(y) * 100, ...
                   sum(errors >= 30) / length(y) * 100);
    
end

