function res =  dataForTable(y, yp)
    R2 = 1 - sum((y - yp) .^ 2)/sum((y - mean(y)) .^ 2);
    MSE = mse(y - yp);
    RMSE = sqrt(MSE);
    CKO = RMSE / (max(y) - min(y)) * 100;
    MAE = mae(y - yp);
    MinAbsErr = min(abs(y - yp));
    MaxAbsErr =  max(abs(y - yp));
    MAPE = mean(abs((y - yp) ./ y)) * 100;
    errors = abs((y - yp) ./ y) * 100;
    Under5PersentPortion = sum(errors < 5) / length(y) * 100;
    Under10PersentPortion = sum(5 <= errors & errors < 10) / length(y) * 100;
    Under20PersentPortion = sum(10 <= errors & errors < 20) / length(y) * 100;
    Under30PersentPortion = sum(20 <= errors & errors < 30) / length(y) * 100;
    Over30PersentPortion = sum(errors >= 30) / length(y) * 100;

    res = sprintf(['R^2: %f\n' ...
       'MSE: %f\n' ...
       'RMSE: %f\n' ...
       'Относительная СКО: %f%%\n' ...
       'MAE: %f\n'...
       'min abs err: %f\n' ...
       'max abs err: %f\n' ...
       'MAPE: %f\n' ...
       'Доля с ошибкой менее 5%%: %f%%\n' ...
       'Доля с ошибкой от 5%% до 10%%: %f%%\n'...
       'Доля с ошибкой от 10%% до 20%%: %f%%\n' ...
       'Доля с ошибкой от 20%% до 30%%: %f%%\n' ...
       'Доля с ошибкой более 30%%: %f%%\n'], ...
       R2, MSE, RMSE, CKO, MAE, MinAbsErr, MaxAbsErr, MAPE,  Under5PersentPortion, Under10PersentPortion, Under20PersentPortion, Under30PersentPortion, Over30PersentPortion);

end
