# Generated by Django 2.2.3 on 2019-07-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserWithKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nicname', models.CharField(db_index=True, max_length=15, unique=True)),
                ('email', models.CharField(db_index=True, max_length=15, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=15)),
            ],
        ),
    ]
