# Generated by Django 2.2.3 on 2019-07-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersList', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWithKey',
        ),
    ]
